In [1]:
import numpy as np
import pandas as pd
np.random.seed(12345)
import matplotlib.pyplot as plt

# 12장 파이썬 모델링 라이브러리
* 모델 fitting
* 모델 scoring
* 데이터 cleaning
* 모델링 도구
  * statsmodels
    * https://www.statsmodels.org/stable/index.html
  * scikit-learn(사이킷런)
    * https://scikit-learn.org/stable

## 12.1 판다스와 모델 코드의 인터페이스
* 모델 개발 과정

1. 데이터 로딩: 판다스를 사용하여 데이터를 로드하고 데이터프레임으로 변환

2. 데이터 전처리: 판다스를 사용하여 데이터를 전처리
  * 피처 엔지니어링(feature engineering)
    
3. 모델 훈련: 판다스 데이터프레임을 모델 훈련에 사용

4. 모델 평가: 판다스를 사용하여 모델 성능을 평가

5. 모델 예측: 판다스 데이터프레임을 사용하여 모델 예측


### feature engineering
* 기계 학습 모델의 성능을 향상시키기 위해 데이터의 원시 특징을 변환하는 프로세스
* 데이터를 더욱 정보량이 풍부하고 예측하기 쉽게 만드는 데 도움이 됨
* 피처 엔지니어링 기술
  * 결측값 처리: 결측값은 모델 성능에 부정적인 영향을 줌
    * 결측값을 평균, 중앙값 또는 최빈값으로 대체
    * 결측값을 포함하는 행을 삭제
      
  * 이상치 처리: 이상치는 모델 성능에 부정적인 영향을 줌
    * 이상치를 처리하는 방법
      * 이상치를 제거
      * 이상치를 변환

  * 피처 스케일링: 피처 스케일링은 모든 피처가 동일한 범위에 있도록 보장
    * 모델이 모든 피처에 동일한 가중치를 부여하는 데 도움
    * 피처 스케일링 기술
      * 표준화: 피처의 평균을 0, 표준 편차를 1로 조정
      * 정규화: 피처의 값이 0 과 1 사이에 있도록 조정

  * 피처 변환: 피처 변환은 피처의 분포를 변경
    * 이는 모델이 피처 간의 관계를 더 잘 학습하는 데 도움
    * 피처 변환 기술
      * 로그 변환: 피처의 값을 로그로 변환
      * 제곱근 변환: 피처의 값을 제곱근으로 변환
      
  * 피처 선택: 피처 선택은 모델에 사용할 피처를 선택
    * 이는 모델의 성능을 향상시키고 과적합을 줄이는 데 도움이 됨
      * 상관 관계 분석: 상관 관계가 높은 피처를 제거
      * 통계적 유의성 검정: 통계적으로 유의미하지 않은 피처를 제거
      * 머신 러닝 알고리즘: 피처 중요도를 평가하는 머신 러닝 알고리즘을 사용하여 피처를 선택

  *  피처 생성: 피처 생성은 새로운 피처를 생성
    * 이는 모델이 데이터의 패턴을 더 잘 학습하는 데 도움.
      * 교차 피처: 기존 피처를 결합하여 새로운 피처를 생성
      * 주성분 분석: 기존 피처의 주성분을 추출하여 새로운 피처를 생성
  

## 교차 검증(Cross-Validation)
* 교차 검증은 머신러닝 모델의 성능을 평가하는 방법 중 하나
* 교차 검증은 데이터셋을 여러 개의 폴드(fold)로 나누고, 각 폴드를 한 번씩 평가 데이터로 사용하는 방법
* 예를 들어, 데이터셋을 5개의 폴드로 나누고 교차 검증을 사용하여 모델의 성능을 평가하면 다음과 같다.
  * 데이터셋을 5개의 폴드로 나눈다
  * 첫 번째 폴드를 평가 데이터로 사용하고, 나머지 4개의 폴드를 학습 데이터로 사용하여 모델을 훈련시킨다.
  * 훈련된 모델을 사용하여 평가 데이터에 대한 예측을 만든다.
  * 예측과 실제 값을 비교하여 모델의 성능을 평가함
  * 두 번째 폴드를 평가 데이터로 사용하고, 나머지 4개의 폴드를 학습 데이터로 사용하여 모델을 훈련시킴.
  * 훈련된 모델을 사용하여 평가 데이터에 대한 예측을 만든다. 예측과 실제 값을 비교하여 모델의 성능을 평가한다.
  * 이 과정을 모든 폴드에 대해 반복한다.

* 교차 검증은 다음과 같은 장점이 있다.
  1) 모델의 성능을 정확하게 평가할 수 있다.
  2) 과적합을 방지할 수 있다.
  3) 하이퍼파라미터 튜닝에 사용할 수 있다.

* 교차 검증은 다음과 같은 단점이 있다.
  * 시간이 오래 걸린다.
  * 계산 자원이 많이 필요

* DataFrame -> Numpy Array 변환
  * df.to_numpy()

In [2]:
# ex
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})
print(data)
print()
print(data.to_numpy())
print(type(data.to_numpy())) #numpy 객체는 한 가지 데이터타입(모두 숫자형)으로 구성
# ndarray : 차원(5,3 )

   x0    x1    y
0   1  0.01 -1.5
1   2 -0.01  0.0
2   3  0.25  3.6
3   4 -4.10  1.3
4   5  0.00 -2.0

[[ 1.    0.01 -1.5 ]
 [ 2.   -0.01  0.  ]
 [ 3.    0.25  3.6 ]
 [ 4.   -4.1   1.3 ]
 [ 5.    0.   -2.  ]]
<class 'numpy.ndarray'>


* Numpy array -> DataFrame (Next class!! 5/22)

In [3]:
# ex
df2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])
df2

one   two  three
0  1.0  0.01   -1.5
1  2.0 -0.01    0.0
2  3.0  0.25    3.6
3  4.0 -4.10    1.3
4  5.0  0.00   -2.0

* 전체 넘파이 ndarray에서 일부 배열만 선택

In [13]:
# ex
df3 = data.copy() #복사
print(df3.to_numpy()) # 파이썬 객체  ndarray

# 독립변수 x설정
df_X = df3.to_numpy()[:, :2]
print(df_X)
print(type(df_X))

# 종속변수 y설정
df_y = df3.to_numpy()[:, -1]
print(df_y)
print(type(df_y))

[[ 1.    0.01 -1.5 ]
 [ 2.   -0.01  0.  ]
 [ 3.    0.25  3.6 ]
 [ 4.   -4.1   1.3 ]
 [ 5.    0.   -2.  ]]
[[ 1.    0.01]
 [ 2.   -0.01]
 [ 3.    0.25]
 [ 4.   -4.1 ]
 [ 5.    0.  ]]
<class 'numpy.ndarray'>
[-1.5  0.   3.6  1.3 -2. ]
<class 'numpy.ndarray'>


In [14]:
df_y = df3.to_numpy()[:, -1]
print(df_y)
print(type(df_y))

[-1.5  0.   3.6  1.3 -2. ]
<class 'numpy.ndarray'>


# 7.5 범주형 데이터(p.325)

* 모델링을 위한 더미 변수 생성하기
  * 통계나 머신러닝 도구를 사용하다 보면 범주형 데이터를 원-핫 인코딩(one-hot encoding)이라고 부르는 더미 변수(가변수, dummy variable)로 변환
  * 범주를 열로 갖는 DataFrame을 생성하는데, 각 열에는 해당 범주의 발생 여부에 따라 0과 1의 값을 갖는다.

* pd.Categorical() 함수
  *  판다스 시리즈나 데이터프레임에서 범주형 데이터 타입을 생성하는 데 사용
  

In [15]:
# ex
data = pd.DataFrame({
    'x0': [1, 2, 3, 4, 5],
    'x1': [0.01, -0.01, 0.25, -4.1, 0.],
    'y': [-1.5, 0., 3.6, 1.3, -2.]})

data['category'] = pd.Categorical(['a', 'b', 'a', 'a', 'b'],
                                  categories=['a', 'b'])
data

x0    x1    y category
0   1  0.01 -1.5        a
1   2 -0.01  0.0        b
2   3  0.25  3.6        a
3   4 -4.10  1.3        a
4   5  0.00 -2.0        b

* pd.get_dummies() 함수
  * 판다스에서 범주형 데이터를 원-핫 인코딩된 피처로 변환하는 데 사용.
  * 원-핫 인코딩은 범주형 데이터를 일련의 이진 피처로 나타내는 기술  
  * 인자
    * prefix: 이 옵션은 원-핫 인코딩된 피처 이름에 사용할 접두사를 지정 

* 원-핫 인코딩은 다음과 같은 다양한 작업에 유용.
  * 머신러닝: 원-핫 인코딩된 피처를 사용하여 머신러닝 모델을 학습할 수 있다.
  * 데이터 분석: 원-핫 인코딩된 피처를 사용하여 범주형 데이터에 대한 통계 분석을 수행할 수 있다.
  * 데이터 시각화: 원-핫 인코딩된 피처를 사용하여 정보성이 풍부하고 시각적으로 매력적인 시각화를 만들 수 있다.
  

In [16]:
dummies = pd.get_dummies(data.category, prefix='category',
                         dtype=float)
print(dummies)
print()

data_with_dummies = pd.concat([data.drop('category', axis=1), dummies], axis =1)

data_with_dummies

   category_a  category_b
0         1.0         0.0
1         0.0         1.0
2         1.0         0.0
3         1.0         0.0
4         0.0         1.0



x0    x1    y  category_a  category_b
0   1  0.01 -1.5         1.0         0.0
1   2 -0.01  0.0         0.0         1.0
2   3  0.25  3.6         1.0         0.0
3   4 -4.10  1.3         1.0         0.0
4   5  0.00 -2.0         0.0         1.0

## 12.3 statsmodels 소개
* https://www.statsmodels.org
* 다양한 종류의 통계 모델 피팅, 통계 테스트 수행, 데이터 탐색, 시각화를 위한 파이썬 라이브러리
* pip install statsmodels
* import statsmodels.api as sm
* import statsmodels.formula.api as smf
* statsmodels 모델
  * 선형 모델, 일반 선형 모델, 로버스트 선형 모델
  * 선형 혼합 효과 모델
  * 분산분석ANOVA 메서드
  * 시계열 처리 및 상태공간 모델
  

In [17]:
# 라이브러리 설치
!pip install statsmodels

### 12.3.1 선형 회귀 모델 예측하기 : OLS
* 선형 회귀 모델 알고리즘 :  최소제곱법(OLS; Ordinary Least Squares)
* API 모듈 임포트해 사용

In [21]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

* np.c_[a1, a2, ..., aN]
  * 여러 개의 배열을 하나의 배열로 결합해야 하는 경우


In [23]:
#ex : 데이터 생성
a = np.array([[1, 2]]) #(1,2) -> 
print(a.shape) #(1, 2)
print(a)

b = np.array([[5, 6]])

c = np.c_[a,b]
print(c)


(1, 2)
[[1 2]]


* np.dot(A, B) 함수
  * 두 개의 벡터를 곱하여 내적을 계산할 때
  * 두 개의 행렬을 곱하여 행렬 곱셈을 수행할 때
  * 행렬과 벡터를 곱하여 행렬-벡터 곱셈을 수행할 때

In [ ]:
# 두 개의 벡터를 곱하여 내적을 계산
a = np.array([1, 2])
b = np.array([3, 4])
c = np.dot(a, b) # elementwise multiplication
print(c)  # 출력: 11 = 1*3 + 2*4

# 두 개의 행렬을 곱하여 행렬 곱셈을 수행
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.dot(a, b)
print(c)  # 출력: [[19 22]
         # [43 50]]

# 행렬과 벡터를 곱하여 행렬-벡터 곱셈을 수행
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
c = np.dot(a, b)
print(c)  # 출력: [17 39]

### [예제] p.541
* 무작위 데이터로 선형 회귀 모델 생성

In [27]:
# 1. Numpy data 생성
# 시드를 설정하면 난수 생성기가 항상 같은 순서로 난수를 생성
rng = np.random.RandomState(12345)

def dnorm(mean, variance, size=1): #정규 분포에서 난수를  생성하는 helper 함수
    if isinstance(size, int):
        size = size,
    return mean + np.sqrt(variance) * rng.standard_normal(*size)

N = 100
# 3개의 features과 100개의 행으로 구성된 행렬 X
X = np.c_[dnorm(0, 0.4, size=N),
          dnorm(0, 0.6, size=N),
          dnorm(0, 0.2, size=N)]

eps = dnorm(0, 0.1, size=N)

W = [0.1, 0.3, 0.5]

# 선형 회귀 모델을 생성.
# X 행렬은 독립 변수이고, y 변수는 종속 변수이며, W 리스트는 회귀 계수
# eps는 오차항
y = np.dot(X,W) + eps

X[:10], y[:10]
X.shape
y.shape

(100,)

In [26]:
dnorm(0, 0.4, size=N).shape  # (100,)
X.shape # (100, 3)
print(y.shape) #(100,)

(100,)


In [34]:
import statsmodels.api as sm

#2. 최소제곱법 선형회귀 모형 선택
# 기존 행렬  X에  Intercept열을 더하기
dfX = sm.add_constant(X)  
# sm.OLS클래스을 이용하여 최소제곱법 선형회귀 모형 선택
model_1 = sm.OLS(y, dfX)


In [36]:
# 3. 모형학습
# fit 메서드로 모형 추정. 
results_1 = model_1.fit() #추정 결과는 별도의 RegressionResults 클래스 객체로 반환

In [32]:
# 선형회귀 모형의 가중치
results_1.params

array([0.03355856, 0.17614872, 0.22482596, 0.51480793])

In [38]:
#선형회귀 모형의 오차
results_1.resid # 100개

array([ 0.43019002, -0.53157637, -0.13210322, -0.1664243 , -0.02840651,
       -0.03754865,  0.46172675, -0.70512128, -0.389283  , -0.15206959,
        0.20864465,  0.34362112, -0.02547815, -0.01584662, -0.06613965,
       -0.2466684 ,  0.19473711, -0.15368098,  0.58982577,  0.33899167,
       -0.1691334 ,  0.09391862,  0.4987464 ,  0.02527616, -0.32014206,
        0.04915143,  0.36285141, -0.540397  , -0.10114742, -0.32726104,
       -0.03178383, -0.55984678, -0.18878223,  0.93075193, -0.17960056,
       -0.24987463,  0.3117442 , -0.43263393,  0.19448595,  0.3020141 ,
        0.2524745 , -0.20284954, -0.22311886,  0.45762566,  0.06346702,
        0.31163719,  0.13098709, -0.16721826, -0.0315735 , -0.41857237,
       -0.14416471, -0.36271356,  0.2998745 ,  0.02668502,  0.32294591,
        0.23281806, -0.11602075, -0.24802696, -0.21042468,  0.3685663 ,
        0.05235366, -0.00861223,  0.17831809, -0.31761102, -0.19729082,
        0.51594113, -0.54648787, -0.17896167,  0.50498212,  0.01

In [39]:
results_1.summary() #결과 리포트용 summary 메서드

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.435
Model:                            OLS   Adj. R-squared:                  0.418
Method:                 Least Squares   F-statistic:                     24.68
Date:                Wed, 22 May 2024   Prob (F-statistic):           6.37e-12
Time:                        15:48:13   Log-Likelihood:                -33.835
No. Observations:                 100   AIC:                             75.67
Df Residuals:                      96   BIC:                             86.09
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0336      0.035      0.952      0.343      -0.036       0.104
x1             0.1761      0.053      3.320      0.001       0.071       0.281
x2             0.2248      0.046      4.851      0.000       0.133       0.317
x3             0.5148      0.082      6.304      0.000       0.353       0.677
==============================================================================
Omnibus:                        4.504   Durbin-Watson:                   2.223
Prob(Omnibus):                  0.105   Jarque-Bera (JB):                3.957
Skew:                           0.475   Prob(JB):                        0.138
Kurtosis:                       3.222   Cond. No.                         2.38
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""